### ISSUE TITLE
description in readme and plugins db are not clear enough

### ISSUE THREAD

**Issue by danmarsden** [santoshndev/local_virus_scanner#3]
The plugins db states "This plugin can be used to scan the uploaded assignment files"

this is not quite correct. The plugin only looks for files in the moodle assignment "submission_files" file area - moodle assignments can store files in different ways within different plugins/submission types. Please improve your plugin description so it is really specific eg something like the following:

This plugin scans files using clamscan that are contained within the "submission_files" area of moodle assignments uploaded in the last 24 hours and generates a report sent via email if any files are detected.

It does not quarantine or remove files.
It does not scan "all" files uploaded to Moodle.

If you want a more detailed antivirus scanning solution you should use the antivirus features built-in to the core Moodle version.

**Comment by santoshndev** [comment]
Hi @danmarsden 
Its fixed now.
